In [1]:
import pandas as pd
import numpy as np

In [3]:
residental_data = pd.read_csv("C:\\Users\\jakub\Documents\\GitHub\\Engineering_Thesis\\Solution\\App\\backend\\models\\data\\residental_buildings.csv", sep=";")
residental_data

            @id     building         name          y          x
0     100725775  residential          NaN  51.062056  17.063406
1     100725809  residential          NaN  51.048806  17.020858
2     100725820  residential          NaN  51.046833  17.025563
3     100725865  residential          NaN  51.063739  17.031691
4     100725952  residential          NaN  51.067540  17.036598
...         ...          ...          ...        ...        ...
4317    5712549  residential  Patio House  51.136438  16.955271
4318   11768963  residential          NaN  51.082459  17.014466
4319   11768964  residential          NaN  51.082364  17.014414
4320   11768965  residential          NaN  51.082270  17.014383
4321   16291071  residential          NaN  51.112389  17.007737

[4322 rows x 5 columns]

In [7]:
residental_data.loc[len(residental_data)] = ["id", "residential", None, 1,2]
residental_data

            @id     building  name          y          x
0     100725775  residential   NaN  51.062056  17.063406
1     100725809  residential   NaN  51.048806  17.020858
2     100725820  residential   NaN  51.046833  17.025563
3     100725865  residential   NaN  51.063739  17.031691
4     100725952  residential   NaN  51.067540  17.036598
...         ...          ...   ...        ...        ...
4319   11768964  residential   NaN  51.082364  17.014414
4320   11768965  residential   NaN  51.082270  17.014383
4321   16291071  residential   NaN  51.112389  17.007737
4322         id  residential  None   1.000000   2.000000
4323         id  residential  None   1.000000   2.000000

[4324 rows x 5 columns]